Repository AY2122S1-CS2103T-T09-2/tp, pull requests merged in 2021-11, with the labels that each got.

#209 Add ruiquan ppp
  docs/AboutUs.md
  docs/team/tanruiquan.md
Labels: type.Task

#218 Fix contHACKS allowing duplicate module lessons
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/modulelesson/ModuleLesson.java
Labels: type.Bug

#227 Remove traces of address book
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/modulelesson/ClearModuleLessonCommand.java
  src/main/java/seedu/address/logic/commands/modulelesson/DeleteModuleLessonCommand.java
  src/main/java/seedu/address/logic/commands/modulelesson/FindModuleLessonCommand.java
  src/main/java/seedu/address/logic/commands/modulelesson/ListModuleLessonCommand.java
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/ClearPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/modulelesson/DeleteModuleLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/modulelesson/FindModuleLessonCommandParser.java
  src/main/java/seedu/address/model/Conthacks.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyConthacks.java
  src/main/java/seedu/address/model/lessoncode/LessonCode.java
  src/main/java/seedu/address/model/modulelesson/UniqueModuleLessonList.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/ModuleCode.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/TeleHandle.java
Labels: type.Task

#220 Update email message constraints
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug

#221 Show warning when adding lesson that clashes with existing lesson
  src/main/java/seedu/address/logic/commands/modulelesson/AddModuleLessonCommand.java
  src/main/java/seedu/address/model/Conthacks.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/modulelesson/LessonTime.java
  src/main/java/seedu/address/model/modulelesson/ModuleLesson.java
  src/main/java/seedu/address/model/modulelesson/UniqueModuleLessonList.java
  src/test/java/seedu/address/logic/commands/modulelesson/AddModuleLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonCommandTest.java
Labels: type.Bug

#230 Add Jason PPP
  docs/AboutUs.md
  docs/team/jason-ng-zq99.md
Labels: type.Task

#208 Fix bug in find person feature
  src/main/java/seedu/address/logic/parser/person/FindPersonCommandParser.java
  src/main/java/seedu/address/model/person/ModuleCodesContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/person/FindPersonCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Story

#231 Update DG to include implementation details about Add feature
  docs/DeveloperGuide.md
  docs/diagrams/ParseAddModuleLessonSequenceDiagram.png
  docs/diagrams/ParseAddModuleLessonSequenceDiagram.puml
  docs/diagrams/ParseAddPersonSequenceDiagram.png
  docs/diagrams/ParseAddPersonSequenceDiagram.puml
  docs/images/ParseAddModuleLessonSequenceDiagram.png
  docs/images/ParseAddPersonSequenceDiagram.png
Labels: type.Task

#215 Prevents duplicated person from being added
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TeleHandle.java
  src/test/data/JsonSerializableConthacksTest/duplicatePersonConthacks.json
  src/test/data/JsonSerializableConthacksTest/typicalPersonsConthacks.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/person/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug
